### ISSUE TITLE
property value can't have length 0

### ISSUE THREAD

**Issue by mishak87** [mqus/go-contentline#1]
Google Calendar export usually contains events with empty properties `DESCRIPTION` and `LOCATION`.

Library returns error `error while parsing component(s): property value can't have length 0:    LOCATION:<HERE>`. [source](https://github.com/mqus/go-contentline/blob/master/lexer.go#L304)

I have not found in RFC 5545 mention about empty properties. Could you allow them?

Hotfix for now is to remove lines matching '^[A-Z]+:$' from input stream.

**Comment by mqus** [comment]
you're completely right. i'll fix this monday or tuesday and add a test.

Thanks for noticing this!

**Comment by mqus** [comment]
Sorry, I completely forgot this issue :-/ 
It should be fixed now. Please reopen this issue if there is more ;)
